### PR TITLE
refactor: improved code readibility

### PR DESCRIPTION
**Pull request by Nkiriobasi**
### What has changed? ✨

Refactored and improved code readability enhancement
I enhanced the code structure and made the getDateTimeFormat function more legible.

### CODE REVIEW

**Comment by KjetilIN** [comment]
@Nkiriobasi Thanks for the PR! But the PR description needs to be more readable for new users/programmers.

**Comment by Nkiriobasi** [comment]
I've made changes

**Review by KjetilIN — APPROVED** [review]
@Nkiriobasi  Looks good! Thanks!

**Comment by KjetilIN** [comment]
@Nkiriobasi  Feel free to star the repository and follow me on github! Thanks!

**Comment by Nkiriobasi** [comment]
Alright, no problem

**Pull request merged**
