### PR TITLE
fix: new properties for .prettierrc file

### PR DESCRIPTION
**Pull request by Mosazghi**
### What has changed? ✨
Had to implement new  / change existing properties on the `.prettierc.json`-file to make formatting docuemts work. 

### How did you solve/implement it? 🧠
Changed the properties.

### CODE REVIEW

**Comment by KjetilIN** [comment]
@Mosazghi What was the error?

**Comment by Mosazghi** [comment]
@KjetilIN I thought I had attached a picture showing the error 😅
Anyway, the error itself will be arbitrary. For example: 
image

**Comment by KjetilIN** [comment]
@all-contributors please add @Mosazghi for bug

**Review by KjetilIN — APPROVED** [review]
LGTM Well done!

**Pull request merged**
