### PR TITLE
Mazemap component

### PR DESCRIPTION
**Pull request by AbdiYus**
### What has changed? ✨
I have added a mazemap component. It will let the companies know where and which room/building we reside in. 
image

### How did you solve/implement it? 🧠
Mazemap has an js api which can ble implementet in react. So i followed their documentation to implement in our website. You can read more about it here: https://api.mazemap.com/js/v2.0.106/docs/#intro 

One important thing to notice about the component, is that it needs to be renderd at the client and not the server. Which causes the problem for fetching other items form the server. But the solution for those situations might be making a function outside of the page.

### CODE REVIEW

**Comment by KjetilIN** [comment]
@AbdiYus This is the build error: 
image

**Comment by KjetilIN** [comment]
@AbdiYus I have removed the git module in the development branch. If you merge the newest changes from development into your code, you will be able to have no issues with deployment!

**Comment by AbdiYus** [comment]
I'm using my brother's computer so I used the wrong github acount. sorry.

**Comment by KjetilIN** [comment]
@AbdiYus Well done! You have a merge conflict you need to resolve, but other than that this looks good!

**Review by KjetilIN — APPROVED** [review]
LGTM

**Pull request merged**
