### PR TITLE
Add route for bedrifter

### PR DESCRIPTION
**Pull request by AbdiYus**
### What has changed? ✨
Implemented new route https://www.startgjovik.no/for-company.  Together with some mock text and a footer.
image

### How did you solve/implement it? 🧠
Folders defines routs in Next, and files define user interface. In order to make a new route, I created a new folder called "for-company", and then added a file called "page.tsx". "page.tsx" is a uniqe file which ONLY can send UI to the webpage in Next. In "page.tsx" I made the function "ForCompany" which returns the mock text and the footer.

### CODE REVIEW

**Comment by KjetilIN** [comment]
@AbdiYus Looks good! However, I think we need to make the path in norwegain. The code itself should be english but the path changed to "for-bedrifter". 

I think that all that needs to change is name of the folder.

I am going to make an issue to make all of the routes in norwegian. Do you want this task? 🤩

(I am also going to look into why the preview is failing, will come back with more info)

**Comment by AbdiYus** [comment]
Changed route name to "for-bedrifter". 

 I can also change the names to norwegian for every route if that is needed.

**Comment by KjetilIN** [comment]
@AbdiYus Could you show with a screenshot that www.startgjovik.no/for-bedrifter is working as aspected? Thanks! :rocket:

**Comment by AbdiYus** [comment]
image

**Review by KjetilIN — APPROVED** [review]
LGTM :rocket:

**Pull request merged**
